apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
type: Opaque
stringData:
  cloud_init: IyEvYmluL2Jhc2gKCk1BU1RFUl9JUD0iNjUuMTA4LjE1NS4xNzgiClRPS0VOPSJLMTA0ZjE4NWU2YmVkYTQ5YzQ1MGNiZGZmNzFlYjkwYWExNjYyMzBhY2VkNmZlZjg3ZjNhMTg4ZTk3ZmMyOWVkZTIzOjpzZXJ2ZXI6NTA1MGY0YTIwYzczYzM5MTgxYTcwZDI1YTI2YTljN2MiCgp3aGlsZSAhIHBpbmcgLWMgMSAtVyAxICR7TUFTVEVSX0lQfTsgZG8KICAgIGVjaG8gIldhaXRpbmcgZm9yICR7TUFTVEVSX0lQfSAtIG5ldHdvcmsgaW50ZXJmYWNlIG1pZ2h0IGJlIGRvd24uLi4iCiAgICBzbGVlcCAxCmRvbmUKCmN1cmwgLXNmTCBodHRwczovL2dldC5rM3MuaW8gfCBLM1NfVVJMPWh0dHBzOi8vJHtNQVNURVJfSVB9OjY0NDMgSzNTX1RPS0VOPSR7VE9LRU59IHNoIC0=
  token: YKhLTGF1etT5cEVxMfxcApUROxhqZanGpJDxah0qy8kvoG1N9O6cX0iaW6Gw0aOx