#!/bin/bash

if [ ${#1} -eq 0 ];
then
    echo "Please set arg with project name to delete: hcloud-server-delete test"
    exit 1
fi


servers=`hcloud server list -l name=${1} -l server=1 -o columns=name | tail -n +2`
for name in $servers;
do
    echo Delete $name
    hcloud server delete $name
done

hcloud ssh-key delete $1 || true