#!/bin/bash

if [ ${#1} -eq 0 ];
then
    echo "Please set arg with project name to delete: hcloud-server-delete test"
    exit 1
fi


servers=`hcloud server list -o=json | jq --arg NAME "$1" -r '.[] | select(.labels.name==$NAME and .labels.server=="1") | .name'`
for name in $servers;
do
    echo Delete $name
    hcloud server delete $name
done

hcloud ssh-key delete $1 || true