name: Publish pypi and docker

on:
  push:
    tags:
    - '*'

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: gawsoft/hcloud-k3sup
    - name: Build the Docker image
      run: |
            docker image build -t gawsoft/hcloud-k3sup .
            # Publish latest
            docker image tag gawsoft/hcloud-k3sup:${{ github.event.ref }} gawsoft/hcloud-k3sup:latest
            docker image push gawsoft/hcloud-k3sup:latest
